version: '3.8'

# to be able to connect on the local unix socket run:
#  mkdir /tmp/slack_bot/mysqld
#  chmod 777 /tmp/slack_bot/mysqld
services:
  app:
    image: courier:0.1
    volumes:
      - /tmp/slack_bot/mysqld:/var/run/mysqld
      - db_data:/var/lib/mysql
    networks:
      - net
    depends_on:
      - db
  db:
    container_name: courier_mysql
    image: mysql:5.7.32
    command: mysqld
    volumes:
      - /tmp/slack_bot/mysqld:/var/run/mysqld
      - db_data:/var/lib/mysql
      - ../DB/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./.env
    networks:
      - net
volumes:
  db_data:

networks:
  net:
