version: '3.8'

services:
  db:
    container_name: courier_mysql
    image: mysql:5.7.32
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./.env

volumes:
  db_data:
