version: '3.9'

services:
  db:
    container_name: cassidy_mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3306:3306'
    env_file:
      - ./.env
volumes:
  db_data:
